### ISSUE TITLE
[Vermutlicher Bug] GS "Leitfaden" auf Beach City

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/Glowarion#102]
Ein neuer Spieler (Pandinchen) wurde auf ein besetztes GS geführt, obwohl mehrere GS frei waren.

**Comment by Glowdragon** [comment]
Das Problem ist dadurch entstanden, dass das besetzte Grundstück keinen Besitzer, aber ein Mitglied hatte. Dies lag daran, dass ich den Spieler zum Grundstück hinzugefügt hatte, ohne anzugeben, dass er als Besitzer hinzugefügt werden soll. Dafür wurde nun der Befehl **/gs + <Spieler> besitzer** implementiert.
