### ISSUE TITLE
Ping- Geräusch bei @-Nachrichten

### ISSUE THREAD

**Issue by Neqiro** [Glowdragon/Glowarion#105]
Wenn ein Spieler mit @<Name> im Chat angesprochen wird, hört er einen kleinen Ping Sound (Level-Up Sound oder der Sound, der spielt, wenn man etwas mit dem Bogen trifft). Dies kann per Befehl abgeschaltet werden.

**Comment by Glowdragon** [comment]
Existiert schon: #5
