### ISSUE TITLE
Teleportation funktioniert nicht

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/Glowarion#29]
Wenn im Creative, funktioniert die teleportation nicht wenn man im Survival keine Hungerkeulen mehr hatte.
Visuell ist es nicht erkennbar das man sich nicht teleportieren kann.
Vorschlag: Im Creative einfach keine Hungerkeulen abziehen oder im Chat eine ansage für den jeweiligen spieler, dass er sich nicht porten kann weil ihm die Hungerkeulen fehlen.

**Comment by Glowdragon** [comment]
Das Problem kann nicht reproduziert werden.
