### ISSUE TITLE
NPC's der Spieler am Spawn(schiff)

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/Glowarion#37]
Die NPC's vom Tutorial, für die Neuen spieler, sammeln sich an einem Punkt auf dem Spawn
https://i.imgur.com/92qRXx5.png

**Comment by Glowdragon** [comment]
In letzter Zeit wurde dieser Bug nicht mehr gesehen. Vielleicht wurde er durch Aufräumarbeiten automatisch behoben.
