### ISSUE TITLE
Inventar und Spielmodus nach dem Reload

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/Glowarion#63]
Nach einem Reload soll das Inventar und der Spielmodus behalten werden.

**Comment by Glowdragon** [comment]
Das Cheatsystem wurde nun so umprogrammiert, dass es Charaktere gibt, die den Kreativmodus aktiviert haben. Andere Charaktere können nicht cheaten. Mit /gm kann man als Abkürzung schnell seinen Charakter wechseln.
