### ISSUE TITLE
Zuschauermodus nach einem Reload

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/Glowarion#69]
Nach einem reload wird der Zuschauer Modus nicht behalten, sondern wird in einen anderen versetzt.

**Comment by Glowdragon** [comment]
Der Zuschauermodus wird in der Form nicht lange existieren. Die Umsetzung der Beibehaltung des Zuschauermodus ist zu aufwändig und wird somit nicht stattfinden.
