### ISSUE TITLE
Schneemänner produzieren keinen Schnee

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/Glowarion#71]
Der Titel sagt alles. Gemeldet von Flurit.

**Comment by Glowdragon** [comment]
> Schneegolems hinterlassen an Orten in Biomen, wo der Temperaturwert weniger als 0,8 beträgt, beim Laufen eine Schicht aus Schnee. Dabei ist dieser Wert zwar z. T. vom Biom abhängig, wird aber letztendlich durch die Höhe bestimmt. So wird ein Schneegolem in der Ebene (Temperatur: 0,8) unterhalb des Meeresspiegels niemals eine Schneespur hinterlassen, aber bereits wenige Blöcke über diesem ist dies der Fall.
https://minecraft-de.gamepedia.com/Schneegolem

Die Ursache des Problems ist also, dass der Schneemann meistens weit unter dem Meeresspiegel ist, wenn wir von der Hauptwelt reden. Denn diese hat ja einen Meeresspiegel von 19, wobei Minecraft trotzdem von 63 ausgeht.

Lösungsvorschlag: Den Schnee künstlich per Plugin spawnen.

**Comment by Zartrix** [comment]
Wurde behoben(?)
