### ISSUE TITLE
[Fun] Muss los Elytra (Elytralos)

### ISSUE THREAD

**Issue by Zartrix** [Glowdragon/Glowarion#80]
Beim Abflug wird im Lokalen Chat "Bruder muss los" gesendet.

**Comment by Glowdragon** [comment]
Wie soll das Crafting-Rezept für das Item aussehen?

**Comment by Glowdragon** [comment]
![image](https://user-images.githubusercontent.com/3618527/47270222-d4e6a300-d568-11e8-81dc-c6a9249ef4f6.png)
_Von Zartrix vorgeschlagen_
