### ISSUE TITLE
Ticketsystem für Support und Bugs

### ISSUE THREAD

**Issue by Neqiro** [Glowdragon/Glowarion#86]
Der Befehl "/ticket support" oder "/ticket hilfe" öffnet ein Buch, in dem der anfragende Spieler sein Problem kurz beschreiben kann.
Dies macht es einfacher für Supporter zu entscheiden, ob sie im jeweiligen Fall helfen können. Außerdem können so die Supportanfragen geloggt werden, wodurch häufiger auftretende Probleme erkannt und gelöst werden können.

Der Befehl "/ticket bug" öffnet ein Buch, in dem der anfragende Spieler einen Bug und Schritte zum Reproduzieren angeben kann. Anschließend wird der Bugreport von einem entsprechenden Verantwortlichen begutachtet, der ein Issue erstellt und den Bug in eine Schwere-Klasse einteilt. Je nach Schwere des Bugs wird der Melder automatisch belohnt.

Der Befehlt "/ticket" öffnet ein Buch, welches eine Auswahlmöglichkeit für alle Ticketarten bietet.

**Comment by Neqiro** [comment]
Eventuell könnte man über dieses System auch über eine dritte Ticketart andere Spieler für unerwünschtes Verhalten melden.

**Comment by Glowdragon** [comment]
Die Eingabe über ein Buch zu regeln wäre nicht möglich. Wie wäre es mit der Website oder dem Chat?

**Comment by Neqiro** [comment]
Die Website ist blöd, weil man dazu das Spiel verlassen muss. Man sollte versuchen möglichst alles auf ein Medium (das Spiel selbst) zu beschränken und die Website nur als Zusatz anzubieten, sodass sie nice-to-have ist, aber nicht zwangsweise zu nutzen ist.

Der Chat wäre okay, ist aber nicht schön, auf Grund der Limitierung auf eine sichtbare Zeile und das Zeichenlimit.

Ich würde mir Wünschen, dass, wenn möglich, Bücher wieder als Inputmöglichkeit zur Verfügung gestellt werden, da diese es auf sehr schöne Weise erlauben längere oder mehrzeilige Text übersichtlich und strukturiert ingame einzugeben.

**Comment by Glowdragon** [comment]
Wie gesagt, das Buch wird für Spieler nie zugänglich sein. Daher abgelehnt.
Sowieso wird angestrebt, sofortigen Support anzubieten. Falls dies nicht möglich sein sollte, kann der Spieler in Zukunft über ein Formular auf der Website sich an das Team wenden und evtl. Anhänge (Screenshots, Videos) hochladen.
